### PR TITLE
Clarify how where plugins are loaded, and how they can be set up for development

### PR DESCRIPTION
**Pull request by apotek**
From a lando slack thread. 

@[apotek](https://app.slack.com/team/U0375KF80CS) I think it would also help if that paragraph showed an example of: 1) creating and placing your plugin, both to override an existing plugin, and one that is a new one, and 2) Some ~/.lando/config.yml examples. The file just contains a yml object in {} notation.

What do you think? Any one of these three suggestions would help make that paragraph more clear to a newbie. I really struggled with it yesterday, when it is actually so simple.

@[reynoldsalec](https://app.slack.com/team/U2YP6FC8N)  I love the idea of making that section more explicit in the docs; if you had an idea on it would appreciate a PR

[It is really really difficult to not put a link to that video tutorial in these docs](https://www.twitch.tv/videos/1425689833)

### CODE REVIEW

**Comment by pirog** [comment]
@apotek FWIW i think we want to be encouraging people to use the dev docs in each plugin eg https://docs.lando.dev/postgres/development.html, is there something not clear about these docs that we need to change?

**Comment by apotek** [comment]
> @apotek FWIW i think we want to be encouraging people to use the dev docs in each plugin eg https://docs.lando.dev/postgres/development.html, is there something not clear about these docs that we need to change?

Hi @pirog. I saw this issue just got marked stale, and that occasioned me noticing that you had asked me a question. So I apologize for the delay. 

I understand your point about wanting to direct people to the dev docs for each plugin. That makes sense. My goal here though is to clarify some very _general_ things about working on Lando plugins, things that have to do with the Lando plugin framework, not with individual plugins. The docs here are of such a general nature that repeating this information in every readme for every plugin might make the docs difficult to maintain.

I contributed this PR because of things that were unclear to me about the loading and discovery of Lando plugins for developer, and figured clarifying a few points and adding some examples might help another developer. If you don't think the clarifications are helpful, so be it.

**Comment by reynoldsalec** [comment]
I generally think this is a good clarification to explain how "global" loading of custom plugins works. Although we give instructions on app-specific loading of custom plugins in the docs for each service, I've spoken with a lot of people who use these global methods (as do I when developing plugins I want to test across multiple apps). Giving a concrete example of how that works seems wise...@pirog if you don't like the verbosity we could add some shorter example directory locations.

**Comment by pirog** [comment]
I think the idea for Lando 4 is that we will have a centralized place for "developer docs" where we can do a much better job than we did for Lando 3 in documenting and explaining the framework.

**Comment by apotek** [comment]
Closing in favor of non-existent documentation to come.

**Comment by reynoldsalec** [comment]
FWIW I think we should definitely include something like this for now @apotek. I think @pirog's comment confirms that the shortfall your PR here tries to fix is actually even bigger and deserves more attention, but we should probably wait until Lando v4 to dedicate a bunch of time towards creating comprehensive docs for those doing custom Lando development.

For now, a "band-aid" like this PR seems like a good addition to me!

**Pull request closed without merging**
